/*
 * Champion roster — generated from Riot Data Dragon.
 * Patch: 16.17.1   Champions: 173
 *
 * Regenerate after each patch with:  node tools/update-champions.mjs
 *
 * `id` is the Data Dragon key, used to build the square icon URL:
 *   https://ddragon.leagueoflegends.com/cdn/<version>/img/champion/<id>.png
 */
window.DDRAGON_VERSION = '16.17.1';

window.CHAMPIONS = [
  { id: 'Aatrox', name: 'Aatrox', tags: ['Fighter'] },
  { id: 'Ahri', name: 'Ahri', tags: ['Mage', 'Assassin'] },
  { id: 'Akali', name: 'Akali', tags: ['Assassin'] },
  { id: 'Akshan', name: 'Akshan', tags: ['Marksman', 'Assassin'] },
  { id: 'Alistar', name: 'Alistar', tags: ['Tank', 'Support'] },
  { id: 'Ambessa', name: 'Ambessa', tags: ['Fighter', 'Assassin'] },
  { id: 'Amumu', name: 'Amumu', tags: ['Tank', 'Support'] },
  { id: 'Anivia', name: 'Anivia', tags: ['Mage'] },
  { id: 'Annie', name: 'Annie', tags: ['Mage', 'Support'] },
  { id: 'Aphelios', name: 'Aphelios', tags: ['Marksman'] },
  { id: 'Ashe', name: 'Ashe', tags: ['Marksman', 'Support'] },
  { id: 'AurelionSol', name: 'Aurelion Sol', tags: ['Mage'] },
  { id: 'Aurora', name: 'Aurora', tags: ['Mage', 'Assassin'] },
  { id: 'Azir', name: 'Azir', tags: ['Mage', 'Marksman'] },
  { id: 'Bard', name: 'Bard', tags: ['Support', 'Mage'] },
  { id: 'Belveth', name: "Bel'Veth", tags: ['Fighter'] },
  { id: 'Blitzcrank', name: 'Blitzcrank', tags: ['Tank', 'Support'] },
  { id: 'Brand', name: 'Brand', tags: ['Mage', 'Support'] },
  { id: 'Braum', name: 'Braum', tags: ['Tank', 'Support'] },
  { id: 'Briar', name: 'Briar', tags: ['Fighter', 'Assassin'] },
  { id: 'Caitlyn', name: 'Caitlyn', tags: ['Marksman'] },
  { id: 'Camille', name: 'Camille', tags: ['Fighter', 'Assassin'] },
  { id: 'Cassiopeia', name: 'Cassiopeia', tags: ['Mage'] },
  { id: 'Chogath', name: "Cho'Gath", tags: ['Tank', 'Mage'] },
  { id: 'Corki', name: 'Corki', tags: ['Marksman', 'Mage'] },
  { id: 'Darius', name: 'Darius', tags: ['Fighter', 'Tank'] },
  { id: 'Diana', name: 'Diana', tags: ['Fighter', 'Assassin'] },
  { id: 'Draven', name: 'Draven', tags: ['Marksman'] },
  { id: 'DrMundo', name: 'Dr. Mundo', tags: ['Tank', 'Fighter'] },
  { id: 'Ekko', name: 'Ekko', tags: ['Assassin', 'Mage'] },
  { id: 'Elise', name: 'Elise', tags: ['Assassin', 'Mage'] },
  { id: 'Evelynn', name: 'Evelynn', tags: ['Assassin', 'Mage'] },
  { id: 'Ezreal', name: 'Ezreal', tags: ['Marksman', 'Mage'] },
  { id: 'Fiddlesticks', name: 'Fiddlesticks', tags: ['Mage', 'Support'] },
  { id: 'Fiora', name: 'Fiora', tags: ['Fighter', 'Assassin'] },
  { id: 'Fizz', name: 'Fizz', tags: ['Assassin', 'Fighter'] },
  { id: 'Galio', name: 'Galio', tags: ['Tank', 'Mage'] },
  { id: 'Gangplank', name: 'Gangplank', tags: ['Fighter'] },
  { id: 'Garen', name: 'Garen', tags: ['Fighter', 'Tank'] },
  { id: 'Gnar', name: 'Gnar', tags: ['Fighter', 'Tank'] },
  { id: 'Gragas', name: 'Gragas', tags: ['Fighter', 'Mage'] },
  { id: 'Graves', name: 'Graves', tags: ['Marksman'] },
  { id: 'Gwen', name: 'Gwen', tags: ['Fighter'] },
  { id: 'Hecarim', name: 'Hecarim', tags: ['Fighter', 'Tank'] },
  { id: 'Heimerdinger', name: 'Heimerdinger', tags: ['Mage', 'Support'] },
  { id: 'Hwei', name: 'Hwei', tags: ['Mage', 'Support'] },
  { id: 'Illaoi', name: 'Illaoi', tags: ['Fighter', 'Tank'] },
  { id: 'Irelia', name: 'Irelia', tags: ['Fighter', 'Assassin'] },
  { id: 'Ivern', name: 'Ivern', tags: ['Support', 'Mage'] },
  { id: 'Janna', name: 'Janna', tags: ['Support', 'Mage'] },
  { id: 'JarvanIV', name: 'Jarvan IV', tags: ['Fighter', 'Tank'] },
  { id: 'Jax', name: 'Jax', tags: ['Fighter'] },
  { id: 'Jayce', name: 'Jayce', tags: ['Fighter', 'Marksman'] },
  { id: 'Jhin', name: 'Jhin', tags: ['Marksman', 'Mage'] },
  { id: 'Jinx', name: 'Jinx', tags: ['Marksman'] },
  { id: 'Kaisa', name: "Kai'Sa", tags: ['Marksman', 'Mage'] },
  { id: 'Kalista', name: 'Kalista', tags: ['Marksman'] },
  { id: 'Karma', name: 'Karma', tags: ['Mage', 'Support'] },
  { id: 'Karthus', name: 'Karthus', tags: ['Mage'] },
  { id: 'Kassadin', name: 'Kassadin', tags: ['Assassin', 'Mage'] },
  { id: 'Katarina', name: 'Katarina', tags: ['Assassin', 'Mage'] },
  { id: 'Kayle', name: 'Kayle', tags: ['Marksman', 'Mage'] },
  { id: 'Kayn', name: 'Kayn', tags: ['Fighter', 'Assassin'] },
  { id: 'Kennen', name: 'Kennen', tags: ['Mage'] },
  { id: 'Khazix', name: "Kha'Zix", tags: ['Assassin'] },
  { id: 'Kindred', name: 'Kindred', tags: ['Marksman'] },
  { id: 'Kled', name: 'Kled', tags: ['Fighter'] },
  { id: 'KogMaw', name: "Kog'Maw", tags: ['Marksman', 'Mage'] },
  { id: 'KSante', name: "K'Sante", tags: ['Tank', 'Fighter'] },
  { id: 'Leblanc', name: 'LeBlanc', tags: ['Assassin', 'Mage'] },
  { id: 'LeeSin', name: 'Lee Sin', tags: ['Fighter', 'Assassin'] },
  { id: 'Leona', name: 'Leona', tags: ['Tank', 'Support'] },
  { id: 'Lillia', name: 'Lillia', tags: ['Fighter', 'Mage'] },
  { id: 'Lissandra', name: 'Lissandra', tags: ['Mage'] },
  { id: 'Locke', name: 'Locke', tags: ['Assassin', 'Mage'] },
  { id: 'Lucian', name: 'Lucian', tags: ['Marksman', 'Assassin'] },
  { id: 'Lulu', name: 'Lulu', tags: ['Support', 'Mage'] },
  { id: 'Lux', name: 'Lux', tags: ['Mage', 'Support'] },
  { id: 'Malphite', name: 'Malphite', tags: ['Tank', 'Mage'] },
  { id: 'Malzahar', name: 'Malzahar', tags: ['Mage'] },
  { id: 'Maokai', name: 'Maokai', tags: ['Tank', 'Support'] },
  { id: 'MasterYi', name: 'Master Yi', tags: ['Fighter', 'Assassin'] },
  { id: 'Mel', name: 'Mel', tags: ['Mage', 'Support'] },
  { id: 'Milio', name: 'Milio', tags: ['Support', 'Mage'] },
  { id: 'MissFortune', name: 'Miss Fortune', tags: ['Marksman', 'Mage'] },
  { id: 'MonkeyKing', name: 'Wukong', tags: ['Fighter', 'Tank'] },
  { id: 'Mordekaiser', name: 'Mordekaiser', tags: ['Fighter', 'Mage'] },
  { id: 'Morgana', name: 'Morgana', tags: ['Support', 'Mage'] },
  { id: 'Naafiri', name: 'Naafiri', tags: ['Assassin', 'Fighter'] },
  { id: 'Nami', name: 'Nami', tags: ['Support', 'Mage'] },
  { id: 'Nasus', name: 'Nasus', tags: ['Fighter', 'Tank'] },
  { id: 'Nautilus', name: 'Nautilus', tags: ['Tank', 'Support'] },
  { id: 'Neeko', name: 'Neeko', tags: ['Mage', 'Support'] },
  { id: 'Nidalee', name: 'Nidalee', tags: ['Assassin', 'Mage'] },
  { id: 'Nilah', name: 'Nilah', tags: ['Fighter', 'Assassin'] },
  { id: 'Nocturne', name: 'Nocturne', tags: ['Fighter', 'Assassin'] },
  { id: 'Nunu', name: 'Nunu & Willump', tags: ['Tank', 'Mage'] },
  { id: 'Olaf', name: 'Olaf', tags: ['Fighter', 'Tank'] },
  { id: 'Orianna', name: 'Orianna', tags: ['Mage', 'Support'] },
  { id: 'Ornn', name: 'Ornn', tags: ['Tank'] },
  { id: 'Pantheon', name: 'Pantheon', tags: ['Fighter', 'Assassin'] },
  { id: 'Poppy', name: 'Poppy', tags: ['Tank', 'Fighter'] },
  { id: 'Pyke', name: 'Pyke', tags: ['Support', 'Assassin'] },
  { id: 'Qiyana', name: 'Qiyana', tags: ['Assassin'] },
  { id: 'Quinn', name: 'Quinn', tags: ['Marksman', 'Assassin'] },
  { id: 'Rakan', name: 'Rakan', tags: ['Support'] },
  { id: 'Rammus', name: 'Rammus', tags: ['Tank'] },
  { id: 'RekSai', name: "Rek'Sai", tags: ['Fighter', 'Tank'] },
  { id: 'Rell', name: 'Rell', tags: ['Tank', 'Support'] },
  { id: 'Renata', name: 'Renata Glasc', tags: ['Support', 'Mage'] },
  { id: 'Renekton', name: 'Renekton', tags: ['Fighter', 'Tank'] },
  { id: 'Rengar', name: 'Rengar', tags: ['Assassin', 'Fighter'] },
  { id: 'Riven', name: 'Riven', tags: ['Fighter', 'Assassin'] },
  { id: 'Rumble', name: 'Rumble', tags: ['Fighter', 'Mage'] },
  { id: 'Ryze', name: 'Ryze', tags: ['Mage'] },
  { id: 'Samira', name: 'Samira', tags: ['Marksman', 'Assassin'] },
  { id: 'Sejuani', name: 'Sejuani', tags: ['Tank'] },
  { id: 'Senna', name: 'Senna', tags: ['Support', 'Marksman'] },
  { id: 'Seraphine', name: 'Seraphine', tags: ['Support', 'Mage'] },
  { id: 'Sett', name: 'Sett', tags: ['Fighter', 'Tank'] },
  { id: 'Shaco', name: 'Shaco', tags: ['Assassin'] },
  { id: 'Shen', name: 'Shen', tags: ['Tank'] },
  { id: 'Shyvana', name: 'Shyvana', tags: ['Fighter', 'Tank'] },
  { id: 'Singed', name: 'Singed', tags: ['Tank', 'Mage'] },
  { id: 'Sion', name: 'Sion', tags: ['Tank', 'Fighter'] },
  { id: 'Sivir', name: 'Sivir', tags: ['Marksman'] },
  { id: 'Skarner', name: 'Skarner', tags: ['Tank', 'Fighter'] },
  { id: 'Smolder', name: 'Smolder', tags: ['Marksman', 'Mage'] },
  { id: 'Sona', name: 'Sona', tags: ['Support', 'Mage'] },
  { id: 'Soraka', name: 'Soraka', tags: ['Support', 'Mage'] },
  { id: 'Swain', name: 'Swain', tags: ['Mage', 'Fighter'] },
  { id: 'Sylas', name: 'Sylas', tags: ['Mage', 'Assassin'] },
  { id: 'Syndra', name: 'Syndra', tags: ['Mage'] },
  { id: 'TahmKench', name: 'Tahm Kench', tags: ['Support', 'Tank'] },
  { id: 'Taliyah', name: 'Taliyah', tags: ['Mage', 'Support'] },
  { id: 'Talon', name: 'Talon', tags: ['Assassin'] },
  { id: 'Taric', name: 'Taric', tags: ['Support', 'Fighter'] },
  { id: 'Teemo', name: 'Teemo', tags: ['Marksman', 'Assassin'] },
  { id: 'Thresh', name: 'Thresh', tags: ['Support', 'Fighter'] },
  { id: 'Tristana', name: 'Tristana', tags: ['Marksman', 'Assassin'] },
  { id: 'Trundle', name: 'Trundle', tags: ['Fighter', 'Tank'] },
  { id: 'Tryndamere', name: 'Tryndamere', tags: ['Fighter', 'Assassin'] },
  { id: 'TwistedFate', name: 'Twisted Fate', tags: ['Mage'] },
  { id: 'Twitch', name: 'Twitch', tags: ['Marksman', 'Assassin'] },
  { id: 'Udyr', name: 'Udyr', tags: ['Fighter', 'Tank'] },
  { id: 'Urgot', name: 'Urgot', tags: ['Fighter', 'Tank'] },
  { id: 'Varus', name: 'Varus', tags: ['Marksman', 'Mage'] },
  { id: 'Vayne', name: 'Vayne', tags: ['Marksman', 'Assassin'] },
  { id: 'Veigar', name: 'Veigar', tags: ['Mage'] },
  { id: 'Velkoz', name: "Vel'Koz", tags: ['Mage'] },
  { id: 'Vex', name: 'Vex', tags: ['Mage'] },
  { id: 'Vi', name: 'Vi', tags: ['Fighter', 'Assassin'] },
  { id: 'Viego', name: 'Viego', tags: ['Assassin', 'Fighter'] },
  { id: 'Viktor', name: 'Viktor', tags: ['Mage'] },
  { id: 'Vladimir', name: 'Vladimir', tags: ['Mage'] },
  { id: 'Volibear', name: 'Volibear', tags: ['Fighter', 'Tank'] },
  { id: 'Warwick', name: 'Warwick', tags: ['Fighter', 'Tank'] },
  { id: 'Xayah', name: 'Xayah', tags: ['Marksman'] },
  { id: 'Xerath', name: 'Xerath', tags: ['Mage'] },
  { id: 'XinZhao', name: 'Xin Zhao', tags: ['Fighter', 'Assassin'] },
  { id: 'Yasuo', name: 'Yasuo', tags: ['Fighter', 'Assassin'] },
  { id: 'Yone', name: 'Yone', tags: ['Assassin', 'Fighter'] },
  { id: 'Yorick', name: 'Yorick', tags: ['Fighter', 'Tank'] },
  { id: 'Yunara', name: 'Yunara', tags: ['Marksman'] },
  { id: 'Yuumi', name: 'Yuumi', tags: ['Support', 'Mage'] },
  { id: 'Zaahen', name: 'Zaahen', tags: ['Fighter'] },
  { id: 'Zac', name: 'Zac', tags: ['Tank', 'Fighter'] },
  { id: 'Zed', name: 'Zed', tags: ['Assassin'] },
  { id: 'Zeri', name: 'Zeri', tags: ['Marksman'] },
  { id: 'Ziggs', name: 'Ziggs', tags: ['Mage'] },
  { id: 'Zilean', name: 'Zilean', tags: ['Support', 'Mage'] },
  { id: 'Zoe', name: 'Zoe', tags: ['Mage', 'Support'] },
  { id: 'Zyra', name: 'Zyra', tags: ['Mage', 'Support'] }
];
